### PR TITLE
Move EdDSA to its own file.

### PR DESCRIPTION
**Pull request by Mischala**
I made a mistake in my understanding when I originally implemented EdDSA.

EdDSA is a different algo than ECDSA, involving different keys, and different operations.

Such that I think it belongs in its own Crypto provider, as not to confuse downstream users.

### CODE REVIEW

**Comment by TJKoury** [comment]
@mischala Do you want help getting this done?

**Comment by Mischala** [comment]
Err  there was nothing stopping it. 
but now there are conflicts.
i will remerge.

**Comment by Mischala** [comment]
Second thought, there is a lot to merge here, and sadly this has fallen off my priority list.
@TJKoury if you would like to get these changes merged... or even make these changes again with the new state of the project, be my guest :D

**Comment by TJKoury** [comment]
@Mischala Copy all, will take a look!

**Pull request closed without merging**
